keys:
  - &users
    - &notoh age1ckvmyqkwk69j64ev3fmckytz6k2dv79z4gn5qf6gxqyevp5yjfesdfkxmn
  - &hosts
    - &tsuki age19l9yutk47w8hdqyzy8p3ygxv7ql6dk42rswshxe7kj0kd28wxsyqxtscl7
    - &hime age1cmsu3ggxndzqdxvnc84g6f6skjgrt64kvjpj9qag5qxa2k9mf95svqp4aj
    - &sutakku age1hd6upymmne2wf7ws8unrl2fnrwgq46u373tyjq643lgftjwpf45qm30l5s
    - &sakura age1vzjyhapn9mqs6x0xwf2xfqaxtlts2dkxt3uudmv7p5868f4jcgrqgqdts

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *notoh