variables:
  - &when_path
    - "*.nix"

pipeline:
  check:
    image: nixos/nix
    commands:      
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix flake check
    when:
      path: *when_path
  fmt:
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - nix run nixpkgs#alejandra -- -c .
    when:
      path: *when_path
